[package]
name = "web-scrape"
version = "0.0.0"
description = "This library aids in scraping data from the web."
readme = "README.md"
repository = "https://github.com/nikdeapen/web-scrape"
homepage = "https://github.com/nikdeapen/web-scrape"
authors = ["Nik Deapen <nik@deapen.com>"]
edition = "2021"
license = "MIT"

[dependencies]
bytes = "1.10.0"
clerr = "0.2.0"
colored = "3.0.0"
enc = { version = "0.10.0", features = ["base-64", "hex"] }
file-storage = "0.2.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.23.1"
web-url = "0.6.0"
